/* ads124s08_impl.hpp
 *
 * Implements the ADS124S08 software interface defined in ads124s08.hpp.
 *
 * Copyright (C) 2026 Project ALTAIR
 *
 * This file is part of ALTAIR Photdiode Readout V26 Testing.
 *
 * ALTAIR Photdiode Readout V26 Testing is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * ALTAIR Photdiode Readout V26 Testing is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ALTAIR Photdiode Readout V26 Testing.
 * If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef ALTAIR_PD_ADS124S08_IMPL_HPP
#define ALTAIR_PD_ADS124S08_IMPL_HPP

#include <pico/time.h>

#include "altair/ads124s08.hpp"
#include "altair/consteval_utils.hpp"
#include "altair/pins.hpp"

namespace altair {

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::init_adc() {
    // Wait for the ADC to power up.
    sleep_us(DELAY_2p2MS);

    // Reset the ADC with the RESET pin to erase any kind of state it might
    // already have.
    reset_adc(true);

    // Check the status register to see if the device is ready.
    std::uint8_t status {read_single_register(RegAddr::STATUS)};
    if(status & to_u8(StatusMask::nRDY)) {
        return false; // Device not ready yet.
    }

    // Reset POR event.
    write_single_register(RegAddr::STATUS, 0x00);

    auto init_registers {reg_mirr_};

    // Read back all the registers.
    read_multiple_registers(nullptr, RegAddr::ID, NUM_REGISTERS);

    // We now check all the "configuration" registers (INPMUX through SYS). If
    // any of them are off from what we think they are, we say initialization
    // failed.
    // This is the most likely place to realize that the ADC might not be
    // present.
    for(std::uint8_t i {to_u8(RegAddr::INPMUX)};
        i <= to_u8(RegAddr::SYS); ++i
    ) {
        if(init_registers[i] != reg_mirr_[i]) {
            return false;
        }
    }

    // Now that we know the ADC exists, we reconfigure it to a reasonable
    // default for the readout boards, reusing the memory from init_registers.

    // Measure AIN5 (TIA) minus AIN0 (2V5)
    init_registers[to_u8(RegAddr::INPMUX)] =
        to_u8(PChannels::AIN5) | to_u8(NChannels::AIN0);

    // DELAY gives the delay between any of the following actions and the first
    // A-D conversion happening:
    // - Done sending a START command
    // - STRT pin rising edge
    // - Writing to certain registers not in standby or power-down modes
    // It's in units of TMOD = 16 TCLK (approx 3.9us). Default of 14 TMOD is
    // fine.

    // The ADC has a programmable gain amplifier that we disable by default.
    // This can be used to increase resolution somewhat at the cost of noise
    // sensitivity and full-scale range. Our noise is almost never low enough
    // to make using it on a 24-bit ADC worthwhile, even if there are zero
    // sources of noise between the photodiode and the ADC input pin.

    // Thus the PGA register is set to 0x00.
    init_registers[to_u8(RegAddr::PGA)] = 0;

    // We disable global chopping, which reverses the polarity of the
    // differential measurement every sample and gives averages of every
    // consecutive pair of measurements, to minimize offset voltage and offset
    // drift. It divides our output sample rate by 3 with the sinc^3 filter,
    // since the inputs need to settle every time they are switched (whereas
    // this only happens on the first conversion without global chop).

    // We choose to use an external clock (generated by an SiT1602B family
    // 4.096MHz oscillator and buffered by an LMK1C1103 clock buffer on the
    // Sergeant and sent through the board-stacking header for the Soldier).

    // We set up continuous conversions for now, instead of single-shot.

    // We use the sinc^3 filter for its improved noise performance compared to
    // the low-latency filter. The latter would be useful if we want to e.g.
    // rapidly check 4V9 (AIN2), PD_TMP (AIN7), and BRD_TMP (AIN6) between TIA
    // (AIN5) measurements, at the cost of additional noise.

    // We sample at a nominal rate of 2.5 samples per second. With our settings
    // described above, this leads to the first sample taking a little over
    // 1200ms and every subsequent sample taking 400ms.

    init_registers[to_u8(RegAddr::DATARATE)] =
        to_u8(DatarateMask::CLKSEL_EXT) | to_u8(DatarateMask::CONVMODE_CONT)
        | to_u8(DatarateMode::DR_2_5);

    // We do not enable sending the STATUS flags along with converted values,
    // so we disable the voltage reference flags that can tell us if the
    // reference ends up in particular voltage ranges.

    // We disable both positive and negative reference buffers as is
    // recommended when use the internal 2.5V reference.

    // We use the internal 2.5V reference instead of an external one.

    // We set the 2.5V reference to always be on, even in power-down mode,
    // because otherwise the LT1991s have effectively an open circuit on one
    // input.

    init_registers[to_u8(RegAddr::REF)] =
        to_u8(RefSetting::FLAG_REF_DISABLE)
        | to_u8(RefSetting::REFP_BYP_DISABLE)
        | to_u8(RefSetting::REFN_BYP_DISABLE) | to_u8(RefSetting::REFSEL_INT)
        | to_u8(RefSetting::REFINT_ON_ALWAYS);

    // We leave the PGA output rail flag disabled because we aren't monitoring
    // STATUS or using the PGA.

    // The low-side power switch exists between two pins that we connect to the
    // same net, so we leave it closed even in power-down mode. (It is there
    // for resistive bridge sensors, which is not at all what we have.)

    // We set the excitation current sources to 50 microamps. Our thermistors
    // can only carry up to 100 microamps, so most of the IMAG options will not
    // work at all for us.

    init_registers[to_u8(RegAddr::IDACMAG)] =
        to_u8(IdacmagSetting::PSW_CLOSED) | to_u8(IdacmagSetting::MAG_50);

    // We use both current sources, sending one to AIN6 for the board
    // thermistor and the other to AIN7 for the photodiode thermistor.

    init_registers[to_u8(RegAddr::IDACMUX)] =
        to_u8(Idac2Output::A7) | to_u8(Idac1Output::A6);

    // Writing zero to VBIAS sets its level to 1/2 AVDD (2.5V) and disconnects
    // it from everything, effectively disabling it. (It is not useful at least
    // for how we routed the board, since we use the internal reference to get
    // 2.5V for the LT1991s.)

    init_registers[to_u8(RegAddr::VBIAS)] = 0x00;

    // The ADC has some system monitor measurement channels that we don't touch
    // for now.

    // The ADC can calibrate for system offset, system gain, and selff offset.
    // These correspond to the SYOCAL, SYGCAL, and SFOCAL commands
    // respectively, and the sample size options are set here. We stick to the
    // default of 8 samples.

    // As an aside, from the datasheet and our schematics, we would likely
    // want to:
    // - jump TP8 and TP9 and set INPMUX to AIN1 | AIN0 to run SYOCAL; or
    // - jump TP2 and TP8 and set INPMUX to AIN1 | AIN0 to run SYGCAL.
    // SFOCAL happens entirely internally and would not need manual setup
    // beyond running the command.

    // We enable SPI timeout as a robustness measure. If the Pico is reset
    // while communicating with an ADC, the ADC will not try to interpret
    // an incomplete command if it takes more than 8ms (or 32768/FCLK) to
    // send a byte to the ADC.

    // We enable CRC, which lets us check if we received the correct conversion
    // data.

    // We do not enable SENDSTAT because we are not monitoring any of its
    // flags.

    init_registers[to_u8(RegAddr::VBIAS)] =
        to_u8(SysSetting::CALSAMPLE_8) | to_u8(SysSetting::TIMEOUT_ENABLE)
        | to_u8(SysSetting::CRC_ENABLE);

    // The GPIO control registers are not contiguous with the others, so we
    // write those 8 config registers and skip over the 6 calibration value
    // registers.
    if(!write_multiple_registers(
        RegAddr::INPMUX, &init_registers[to_u8(RegAddr::INPMUX)], 8
    )) {
        return false; // write_multiple_registers failed somehow.
    }

    // All 4 ADC GPIOs are outputs, so the top half of GPIODAT is all zeroes.
    // In the bottom half, we set GPIO0 to 1 and the rest to 0 to enable
    // reverse bias and leave all the relays open.
    init_registers[to_u8(RegAddr::GPIODAT)] = 0x01;

    // We configure each GPIO pin as GPIO instead of analog input.
    init_registers[to_u8(RegAddr::GPIOCON)] =
        to_u8(GpioConf::GPIO0) | to_u8(GpioConf::GPIO1)
        | to_u8(GpioConf::GPIO2) | to_u8(GpioConf::GPIO3);

    // Write the last of the configuration.
    if(!write_multiple_registers(
        RegAddr::GPIODAT, &init_registers[to_u8(RegAddr::GPIODAT)], 2
    )) {
        return false; // write_multiple_registers failed somehow.
    }

    // Initialization was successful.
    return true;
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::read_converted_data(
    std::int32_t* result, std::uint8_t* status, ReadMode mode
) const {
    // Don't read anything if result is null.
    if(!result) {
        return false;
    }

    std::uint8_t byte_count {DATA_LENGTH};
    std::uint8_t data_offset {0};
    // Buffers for the duplex SPI communication.
    std::array<std::uint8_t, 6> transmit {};
    std::array<std::uint8_t, 6> receive {};

    // CRC comes after data.
    bool crc_enabled {is_crc_set()};
    if(crc_enabled) {
        ++byte_count;
    }

    // Status comes before data.
    bool status_enabled {is_sendstat_set()};
    if(status_enabled) {
        ++byte_count;
        ++data_offset;
    }

    // If we send a RDATA command, then the ADC will wait until after the first
    // byte to begins sending data on MISO.
    if(mode == ReadMode::COMMAND) {
        transmit[0] = to_u8(Opcode::RDATA);
        ++byte_count;
        ++data_offset;
    }

    // SPI communication
    gpio_put(to_u32(CS), 0);
    spi_write_read_blocking(SPI, transmit.data(), receive.data(), byte_count);
    gpio_put(to_u32(CS), 1);

    // Get status. Note that we don't update the register mirror here even
    // though we reasonably could, to keep this function const without hacks.
    if(status && status_enabled) {
        *status = receive[data_offset - 1];
    }

    // Get data
    std::uint32_t result_unsigned {
        static_cast<std::uint32_t>(receive[data_offset]) << 16
        | static_cast<std::uint32_t>(receive[data_offset + 1]) << 8
        | static_cast<std::uint32_t>(receive[data_offset + 2])
    };

    // We shift data left and right to sign-extend the signed code.
    *result = static_cast<std::int32_t>(result_unsigned << 8) >> 8;

    // Get CRC
    if(crc_enabled) {
        std::uint8_t adc_crc {receive[byte_count - 1]};
        // Prepend STATUS to the code if needed.
        if(status_enabled) {
            result_unsigned |= (receive[data_offset - 1] << 24);
        }
        return check_crc(result_unsigned, adc_crc);
    }

    return true;
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
std::uint8_t Adc<strt_pin, drdy_pin, cs_pin>::read_single_register(
    RegAddr address
) {
    // Make arrays to send and receive data.
    std::array<std::uint8_t, COMMAND_LENGTH + 1> transmit {
        static_cast<std::uint8_t>(
            to_u8(Opcode::RREG) | static_cast<std::uint8_t>(address)
        ), 0, 0
    };
    std::array<std::uint8_t, COMMAND_LENGTH + 1> receive {};

    // Run the duplex SPI communication.
    gpio_put(to_u32(CS), 0);
    spi_write_read_blocking(
        SPI, transmit.data(), receive.data(), COMMAND_LENGTH  + 1
    );
    gpio_put(to_u32(CS), 1);

    // Update the local mirror.
    reg_mirr_[static_cast<std::uint8_t>(address)] = receive[COMMAND_LENGTH];
    // Return the register value.
    return receive[COMMAND_LENGTH];
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::read_multiple_registers(
    std::uint8_t* out, RegAddr base, std::uint8_t count
) {
    // Check preconditions.
    if(static_cast<std::uint8_t>(base) + count > NUM_REGISTERS || !count) {
        return false;
    }

    // Make arrays to send and receive data.
    std::array<std::uint8_t, COMMAND_LENGTH + NUM_REGISTERS> transmit {};
    std::array<std::uint8_t, COMMAND_LENGTH + NUM_REGISTERS> receive {};
    // Set up the opcode and "operands" (base and count).
    transmit[0] = to_u8(Opcode::RREG) | static_cast<std::uint8_t>(base);
    transmit[1] = count - 1;

    // Run the duplex SPI communication.
    // Random aside: This is only incidentally safe because of the SPI timeout
    // on the ADC. If exceptions are enabled (they are not here at this time),
    // asserting CS chould probably be wrapped in a minimal RAII struct.
    gpio_put(to_u32(CS), 0);
    spi_write_read_blocking(
        SPI, transmit.data(), receive.data(), COMMAND_LENGTH + count
    );
    gpio_put(to_u32(CS), 1);

    // Update the local mirror.
    for(std::uint8_t i {0}; i < count; ++i) {
        std::uint8_t j {static_cast<std::uint8_t>(
            i + static_cast<std::uint8_t>(base)
        )};
        reg_mirr_[j] = receive[COMMAND_LENGTH + i];

        // Give the caller the register contents if they want them.
        if(out) {
            out[i] = receive[COMMAND_LENGTH + i];
        }
    }
    // Communication is successful as far as we can tell.
    return true;
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
void Adc<strt_pin, drdy_pin, cs_pin>::reset_adc(bool use_pin) {
    if(use_pin) {
        gpio_put(to_u32(RESET), 0);
        sleep_us(DELAY_4TCLK);
        gpio_put(to_u32(RESET), 1);
    } else {
        std::uint8_t command {to_u8(Opcode::RESET)};

        gpio_put(to_u32(CS), 0);
        spi_write_blocking(SPI, &command, 1);
        gpio_put(to_u32(CS), 1);
    }

    // In both cases, a reset takes 1ms or 4096/FCLK to finish, so we need to
    // wait for that long.
    sleep_us(DELAY_4096TCLK);

    // The main benefit of resetting is restoring register defaults, done here.
    restore_register_defaults();
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::send_command(Opcode opcode) const {
    // Check for the unsupported opcodes that must be sent with their special
    // functions.
    if(opcode == Opcode::RREG || opcode == Opcode::WREG
        || opcode == Opcode::RESET
    ) {
        return false;
    }

    std::uint8_t command {static_cast<std::uint8_t>(opcode)};

    gpio_put(to_u32(CS), 0);
    spi_write_blocking(SPI, &command, 1);
    gpio_put(to_u32(CS), 1);

    // Communication succeeded.
    return true;
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
void Adc<strt_pin, drdy_pin, cs_pin>::start_conversions(bool use_pin) const {
    // Wake up the device if it was in POWERDOWN.
    send_command(Opcode::WAKEUP);

    if(use_pin) {
        gpio_put(to_u32(STRT), 1);
    } else {
        send_command(Opcode::START);
    }
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
void Adc<strt_pin, drdy_pin, cs_pin>::stop_conversions(bool use_pin) const {
    if(use_pin) {
        gpio_put(to_u32(STRT), 0);
    } else {
        send_command(Opcode::STOP);
    }
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
void Adc<strt_pin, drdy_pin, cs_pin>::write_single_register(
    RegAddr address, std::uint8_t data
) {
    std::array<std::uint8_t, COMMAND_LENGTH + 1> transmit {};
    transmit[0] = to_u8(Opcode::WREG) | static_cast<std::uint8_t>(address);
    transmit[2] = data;

    gpio_put(to_u32(CS), 0);
    spi_write_blocking(SPI, transmit.data(), COMMAND_LENGTH + 1);
    gpio_put(to_u32(CS), 1);

    // Update local mirror.
    reg_mirr_[static_cast<std::uint8_t>(address)] = transmit[COMMAND_LENGTH];
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::write_multiple_registers(
    RegAddr base, std::uint8_t const* data, std::uint8_t count
) {
    // Check preconditions.
    if(!data || !count
        || static_cast<std::uint8_t>(base) + count >= NUM_REGISTERS
    ) {
        return false;
    }

    std::array<std::uint8_t, COMMAND_LENGTH + NUM_REGISTERS> transmit {};
    transmit[0] = to_u8(Opcode::WREG);
    for(std::uint8_t i {0}; i < count; ++i) {
        transmit[COMMAND_LENGTH + i] = data[i];

        // Update local mirror.
        reg_mirr_[static_cast<std::uint8_t>(base) + i] = data[i];
    }

    gpio_put(to_u32(CS), 0);
    spi_write_blocking(SPI, transmit.data(), COMMAND_LENGTH + count);
    gpio_put(to_u32(CS), 1);

    return true;
}

// Private functions

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
std::uint8_t Adc<strt_pin, drdy_pin, cs_pin>::get_register_value(
    RegAddr address
) const {
    return reg_mirr_[static_cast<std::uint8_t>(address)];
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::is_sendstat_set() const {
    return get_register_value(RegAddr::SYS)
        & to_u8(SysSetting::SENDSTATUS_MASK);
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::is_crc_set() const {
    return get_register_value(RegAddr::SYS) & to_u8(SysSetting::CRC_MASK);
}

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
void Adc<strt_pin, drdy_pin, cs_pin>::restore_register_defaults() {
    // This can be written much more concisely once compilers support C++26
    // expansion statements.
    reg_mirr_[to_u8(RegAddr::ID)]       = get_reg_default(RegAddr::ID);
    reg_mirr_[to_u8(RegAddr::STATUS)]   = get_reg_default(RegAddr::STATUS);
    reg_mirr_[to_u8(RegAddr::INPMUX)]   = get_reg_default(RegAddr::INPMUX);
    reg_mirr_[to_u8(RegAddr::PGA)]      = get_reg_default(RegAddr::PGA);
    reg_mirr_[to_u8(RegAddr::DATARATE)] = get_reg_default(RegAddr::DATARATE);
    reg_mirr_[to_u8(RegAddr::REF)]      = get_reg_default(RegAddr::REF);
    reg_mirr_[to_u8(RegAddr::IDACMAG)]  = get_reg_default(RegAddr::IDACMAG);
    reg_mirr_[to_u8(RegAddr::IDACMUX)]  = get_reg_default(RegAddr::IDACMUX);
    reg_mirr_[to_u8(RegAddr::VBIAS)]    = get_reg_default(RegAddr::VBIAS);
    reg_mirr_[to_u8(RegAddr::SYS)]      = get_reg_default(RegAddr::SYS);
    reg_mirr_[to_u8(RegAddr::OFCAL0)]   = get_reg_default(RegAddr::OFCAL0);
    reg_mirr_[to_u8(RegAddr::OFCAL1)]   = get_reg_default(RegAddr::OFCAL1);
    reg_mirr_[to_u8(RegAddr::OFCAL2)]   = get_reg_default(RegAddr::OFCAL2);
    reg_mirr_[to_u8(RegAddr::FSCAL0)]   = get_reg_default(RegAddr::FSCAL0);
    reg_mirr_[to_u8(RegAddr::FSCAL1)]   = get_reg_default(RegAddr::FSCAL1);
    reg_mirr_[to_u8(RegAddr::FSCAL2)]   = get_reg_default(RegAddr::FSCAL2);
    reg_mirr_[to_u8(RegAddr::GPIODAT)]  = get_reg_default(RegAddr::GPIODAT);
    reg_mirr_[to_u8(RegAddr::GPIOCON)]  = get_reg_default(RegAddr::GPIOCON);
}

namespace {

// Helpers to make a look-up table for speeding up CRC checks.
consteval std::uint8_t find_crc_byte(std::uint8_t byte) {
    constexpr std::uint8_t polynomial {0b0000'0111}; // x^8 + x^2 + x + 1

    std::uint8_t crc {byte};

    for(unsigned int i {0}; i < 8; ++i) {
        if(crc & 0b1000'0000) {
            crc = (crc << 1) ^ polynomial;
        } else {
            crc <<= 1;
        }
    }
    return crc;
}

consteval std::array<std::uint8_t, 256> make_crc_table() {
    std::array<std::uint8_t, 256> result {};
    for(std::size_t i {0}; i < 256; ++i) {
        result[i] = find_crc_byte(static_cast<std::uint8_t>(i));
    }
    return result;
}

inline constexpr std::array<std::uint8_t, 256> crc_lut {make_crc_table()};

} // anonymous namespace

template<Pins strt_pin, Pins drdy_pin, Pins cs_pin>
bool Adc<strt_pin, drdy_pin, cs_pin>::check_crc(
    std::uint32_t code, std::uint8_t adc_crc
) {
    std::uint8_t crc {0};

    for(int i {3}; i >= 0; --i) {
        // Add the next byte to the remainder of the previous division.
        crc ^= static_cast<std::uint8_t>(code >> (8 * i));
        // Find the precomputed remainder of dividing this byte by the CRC
        // polynomial (see the above immediate functions).
        crc = crc_lut[crc];
    }

    return crc == adc_crc;
}

} // namespace altair

#endif // ALTAIR_PD_ADS124S08_IMPL_HPP
